### ISSUE TITLE
wrap in a node-webkit container

### ISSUE THREAD

**Issue by hems** [arboleya/ghfm#1]
We could potentially build a node-webkit container for it, so we could have "File ~> Open" or drag 'n drop functionality !

https://github.com/rogerwang/node-webkit

**Comment by arboleya** [comment]
Bring it on :)

**Comment by arboleya** [comment]
Issue inactive for 2 months, I'm closing it. In case you're willing to move forward with this, we can reopen it and discuss it further.

**Comment by hems** [comment]
its more of a suggestion then an issue...
