### ISSUE TITLE
😥🙉Stopped working.. http://localhost:54321 -> Cannot GET /

### ISSUE THREAD

**Issue by mralexgray** [arboleya/ghfm#4]
```

♫  Preview running at http://localhost:54321

/usr/local/lib/node_modules/ghfm/src/render.coffee:46
  if css.length is 0
     ^
TypeError: Cannot read property 'length' of null
    at save (/usr/local/lib/node_modules/ghfm/src/render.coffee:46:6)
    at /usr/local/lib/node_modules/ghfm/src/render.coffee:47:29
    at Request._callback (/usr/local/lib/node_modules/ghfm/src/render.coffee:43:7)
    at Request.self.callback (/usr/local/lib/node_modules/ghfm/node_modules/request/request.js:129:22)
    at Request.EventEmitter.emit (events.js:98:17)
    at Request.<anonymous> (/usr/local/lib/node_modules/ghfm/node_modules/request/request.js:873:14)
    at Request.EventEmitter.emit (events.js:117:20)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/ghfm/node_modules/request/request.js:824:12)
    at IncomingMessage.EventEmitter.emit (events.js:117:20)
    at _stream_readable.js:920:16
```

**Comment by arboleya** [comment]
This is a very strange behavior since the `css` property is always defined as an empty array here:
https://github.com/arboleya/ghfm/blob/master/src/render.coffee#L13

If you can provide any more info about this error, I can investigate ir further.

**Comment by jzaefferer** [comment]
I just ran into this error as well, with this README.md: https://github.com/millermedeiros/esformatter/blob/cb3c560940496aa4134f0eee391bc5ee6c5e8fcb/README.md

My guess is that this broke after the CSS files including on github.com were moved to a different domain:

https://assets-cdn.github.com/assets/github-7c4e0160a9a6df7e77a4753288deba5f372bbbc6.css
https://assets-cdn.github.com/assets/github2-50bd4d5d683bdda80f061b5d079826bd642a2787.css

These don't match the regex on line 42 (anymore?): /https?:\/\/github.+github2?-[0-9a-z]+.css/g

**Comment by arboleya** [comment]
Exactly, the css filepath has changed. The problem is that it could change frequently, so I guess this topic will be revisited every time it changes.

Any ideas on making a "permanent regex"? I mean, this path could change for anything at any time.

**Comment by mralexgray** [comment]
use a link shortener...  and then just change it if it moves...?

**Comment by arboleya** [comment]
Perhaps we can also loop through all present `css` files, check its source and decide which one is right by testing if it has some of the default classes.

**Comment by jzaefferer** [comment]
You could just include all CSS references on github.com, including more than necessary should be a big deal. Then it doesn't matter what the actual paths are.

**Comment by mralexgray** [comment]
I never used this thing.. and now that I can't I'm  **_FIENDING**_ for it, lol.

**Comment by arboleya** [comment]
Include all css is a very smart approach, since it won't do any harm. :) Simplicity ftw.

I've been very very busy but I do plan to fix everything. If anyone doesn't come along first, I should get back to this in about two weeks. Stay tuned :headphones:

**Comment by mralexgray** [comment]
@arboleya  Give me a pointer on where to start... and I'll do it.  Going crazy without it, lol.

**Comment by arboleya** [comment]
@mralexgray Now you can use it again thanks to the @jzaefferer!

@jzaefferer Thanks for the PR, sorry about the huge delay to merge it.
